#
# Makefile for the Linux Wireless network device drivers.
#
obj-$(CONFIG_BROADCOM_WIFI_BT) += bcmdhd/
obj-$(CONFIG_RTL8188ETV) += rtl8188etv/
obj-$(CONFIG_RTL8723BS) += rtl8723bs/
obj-$(CONFIG_RTL8723BS_VQ0) += rtl8723bs_vq0/
obj-$(CONFIG_RTL8723BU) += rtl8723bu/
obj-$(CONFIG_RTL8192CU) += rtl8192cu/
obj-$(CONFIG_RTL8192EU) += rtl8192eu/
